import chalk from "chalk";

export const rgb = r => g => b => s => chalk.rgb(r, g, b)(s)
export const hex = h => s => chalk.hex(h)(s)
export const ansi256 = i => s => chalk.ansi256(i)(s)

export const bgRgb = r => g => b => s => chalk.bgRgb(r, g, b)(s)
export const bgHex = h => s => chalk.bgHex(h)(s)
export const bgAnsi256 = i => s => chalk.bgAnsi256(i)(s)

export const reset = s => chalk.reset(s)
export const bold  = s => chalk.bold(s)
export const dim  = s => chalk.dim(s)
export const italic  = s => chalk.italic(s)
export const underline  = s => chalk.underline(s)
export const overline  = s => chalk.overline(s)
export const inverse  = s => chalk.inverse(s)
export const hidden  = s => chalk.hidden(s)
export const strikethrough  = s => chalk.strikethrough(s)
export const visible  = s => chalk.visible(s)

export const black = s => chalk.black(s)
export const red = s => chalk.red(s)
export const green = s => chalk.green(s)
export const yellow = s => chalk.yellow(s)
export const blue = s => chalk.blue(s)
export const magenta = s => chalk.magenta(s)
export const cyan = s => chalk.cyan(s)
export const white = s => chalk.white(s)

export const gray = s => chalk.gray(s)
export const grey = s => chalk.grey(s)

export const blackBright = s => chalk.blackBright(s)
export const redBright = s => chalk.redBright(s)
export const greenBright = s => chalk.greenBright(s)
export const yellowBright = s => chalk.yellowBright(s)
export const blueBright = s => chalk.blueBright(s)
export const magentaBright = s => chalk.magentaBright(s)
export const cyanBright = s => chalk.cyanBright(s)
export const whiteBright = s => chalk.whiteBright(s)

export const bgBlack = s => chalk.bgBlack(s)
export const bgRed = s => chalk.bgRed(s)
export const bgGreen = s => chalk.bgGreen(s)
export const bgYellow = s => chalk.bgYellow(s)
export const bgBlue = s => chalk.bgBlue(s)
export const bgMagenta = s => chalk.bgMagenta(s)
export const bgCyan = s => chalk.bgCyan(s)
export const bgWhite = s => chalk.bgWhite(s)

export const bgGray = s => chalk.bgGray(s)
export const bgGrey = s => chalk.bgGrey(s)

export const bgBlackBright = s => chalk.bgBlackBright(s)
export const bgRedBright = s => chalk.bgRedBright(s)
export const bgGreenBright = s => chalk.bgGreenBright(s)
export const bgYellowBright = s => chalk.bgYellowBright(s)
export const bgBlueBright = s => chalk.bgBlueBright(s)
export const bgMagentaBright = s => chalk.bgMagentaBright(s)
export const bgCyanBright = s => chalk.bgCyanBright(s)
export const bgWhiteBright = s => chalk.bgWhiteBright(s)
